# Generated by Django 3.2.15 on 2022-09-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxes',
            name='created_by',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
    ]
